---
  - name: start nodeexporter container
    docker_container:
      name: nodeexporter
      image: prom/node-exporter:latest
      ports:
        - 9100:9100
      container_default_behavior: compatibility
      state: started
      restart_policy: always
    become: yes