---
  - name: start nodeexporter container
    docker_container:
      name: nodeexporter
      image: prom/node-exporter:latest
      network_mode: host
      container_default_behavior: compatibility
      state: started
      restart_policy: always
    become: yes