- name: copy over the ssh key
  copy:
    src: '{{ priv_key_path }}'
    dest: /root/.ssh/ri_key
    mode: 0600

# use a custom ssh config to use custom key when ssh to github.com
# CAUTION: overwriting existing ssh config
- name: copy over the ssh config
  copy:
    src:  ssh_config
    dest: /root/.ssh/config
    mode: 0600

- name: clone git repo
  git:
    repo: git@gitserv:amer/resinfra.git
    dest: /resinfra

# probably too open?
- name: set open permissions for git repo
  file:
    dest: /resinfra
    mode: ugo+rwx
    recurse: yes

- name: copy public key
  authorized_key:
    user: consul
    state: present
    key: "{{ lookup('file', '{{pub_key_path}}') }}"

- name: copy private key
  authorized_key:
    user: consul
    state: present
    key: "{{ lookup('file', '{{priv_key_path}}') }}"

- name: copy gcp key
  authorized_key:
    user: consul
    state: present
    key: "{{ lookup('file', '{{gcp_key_path}}') }}"

- name: copy terraform secrets
  authorized_key:
    user: consul
    state: present
    key: "{{ lookup('file', '{{terraform_secret_path}}') }}"
