apiVersion: v1
kind: Namespace
metadata:
  name: wireguard
  labels:
    name: wireguard
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: wireguard-configmap
  namespace: wireguard
#  annotations:
#    security.alpha.kubernetes.io/unsafe-sysctls: net.ipv4.route.min_pmtu=1000,kernel.msgmax=1 2 3
data:
  CLUSTER_NAME: "cb"
  WG_CONFIG: |
    [Interface]
    Address=192.168.1.0/24
    ListenPort=51820
    PrivateKey=8F8Z+2+LzBniqhDy6OeAyOmyXveEGIhfOeUF9g90mXU=
    PostUp=iptables -t nat -A POSTROUTING -s 192.168.1.0/24 -o eth0 -j MASQUERADE
    PostDown=iptables -t nat -D POSTROUTING -s 192.168.1.0/24 -o eth0 -j MASQUERADE

    [Peer]
    PublicKey=O8HmcIcDnavOFGWGAsl+dK0BqimoOuVSDmU+EEwTbRU=
    AllowedIPs= 0.0.0.0/0
  IP_SCRIPT: |
    #wg-quick up wg0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wireguard-deployment
  namespace: wireguard
spec:
  selector:
    matchLabels:
      app: wireguard
  replicas: 1
  template:
    metadata:
      labels:
        app: wireguard
    spec:
      initContainers:
        - name: sysctls
          image: busybox
          command:
            - sh
            - -c
            - sysctl -w net.ipv4.ip_forward=1 && sysctl -w net.ipv4.conf.all.forwarding=1
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
            privileged: true
      containers:
        - name: wireguard
          image: docker.io/amerj/wg:latest
          imagePullPolicy: Always # IfNotPresent, Always, Never
          envFrom:
            - configMapRef:
                name: wireguard-configmap
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - SYS_MODULE
            privileged: true
          ports:
            - containerPort: 51820
              protocol: UDP
---
kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: wireguard
  name: wireguard-service
  namespace: wireguard
spec:
  type: NodePort
  ports:
    - port: 51820
      nodePort: 31000
      protocol: UDP
      targetPort: 51820
  selector:
    app: wireguard
---