- name: Create directory
  file:
    path: /home/resinfra
    state: directory

- name: create the command
  template:
    src: cockroach_start.sh.j2
    dest: /home/resinfra/cockroach_start.sh
    mode: 0700

- name: Slurp hosts file
  slurp:
    src: /home/resinfra/cockroach_start.sh
  register: slurpfile

- name: start cockroachdb container
  docker_container:
    name: cockroachdb
    image: cockroachdb/cockroach:v20.2.3
    # container_default_behavior: compatibility
    ports: 
      - 8080:8080
      - 26257:26257
    volumes:
      - "~/cockroach-data:/cockroach/cockroach-data"
    command: "{{ slurpfile['content'] | b64decode }}"
    state: started
  become: yes