- name: pull cockroachdb image
  docker_image:
    name: cockroachdb/cockroach:v20.2.3 
    source: pull
  become: yes

- name: create the executable
  template:
    src: cockroach_start.sh.j2
    dest: /home/resinfra/cockroach_start.sh
    mode: 0700

- name: start cockroachdb container
  docker_container:
    name: cockroachdb
    image: cockroachdb/cockroach:v20.2.3
    container_default_behavior: compatibility
    ports: 
      - 8080:8080
      - 26257:26257
    volumes:
      - "~/cockroach-data:/cockroach/cockroach-data"
    command: {{ lookup('file', '/home/resinfra/cockroach_start.sh') }}
    state: started
  become: yes