version: "3"
services:
  elasticsearch:
    image: elasticsearch:7.9.3
    # need to specify version. ES docker image has no "latest" tag.
    environment:
    - discovery.type=single-node
    ports:
    - "127.0.0.1:9200:9200"
  kibana:
    image: kibana:7.9.3
    ports:
    - "5601:5601"
    links:
    - elasticsearch
    depends_on:
    - elasticsearch
  logstash:
    image: logstash:7.9.3
    links:
    - elasticsearch
    depends_on:
    - elasticsearch
    ports:
    - "5044:5044"
    - "5045:5045"
