# Only put one IP in here. On this IP the cluster will be created.
# On first start, all nodes must have at least this IP address in their join list.
[cockroach_cluster_initializer]
10.0.1.2

# TODO: dynamic creation of this list
# Changes on this list should also be made on the playbook COCKROACH_JOIN variable
[cockroach_main_servers_hetzner]
10.0.1.2
10.0.1.3
10.0.1.4
[cockroach_main_servers_azure]
10.1.1.2
10.1.1.3
10.1.1.4
[cockroach_main_servers_gcp]
10.2.0.2
10.2.0.3
10.2.0.4
