- name: Add Consul GPG apt Key
  apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    state: present

- name: Get release name
  command: lsb_release -cs
  register: os_release
  changed_when: false

- name: Add consul repository
  apt_repository:
    repo: deb [arch=amd64] https://apt.releases.hashicorp.com {{ os_release.stdout }} main
    state: present

- name: install Consul, Miller (Data processing tool) and jq (JSON query tool)
  apt:
    name:
      - consul
      - miller
      - jq
    state: present
    update_cache: yes

- name: template the config file
  template:
    src: template/config.hcl.j2
    dest: /etc/consul.d/consul.hcl

# we ues consul to publish nodeexporters to prometheus. Prometheus can query consul for a certain service and
# automatically add all nodes to that service name. See also the prometheus role.
- name: copy the node exporter service file
  copy:
    src: files/nodeexporter_service.json
    dest: /etc/consul.d/nodeexporter_service.json

- name: add a consul user for the systemd service
  user:
    name: consul
    state: present

# we create a systemd service for consul
# we use the -bind option to ensure that we are publishing the internal ip address of the node
# for more see: https://www.consul.io/docs/agent/options#_bind
- name: copy over the service file
  template:
    src: consul.service.j2
    dest: /etc/systemd/system/consul.service

- name: copy over the service configuration
  copy:
    src: files/service_monitoring.json
    dest: /etc/consul.d/

- name: copy over the service configuration
  copy:
    src: files/watch_critical_services_sendslack.json
    dest: /etc/consul.d/

- name: copy over sendslack script
  copy:
    src: files/sendslack.sh
    dest: /resinfra/terraform/
    mode: a+x
    owner: consul

- name: copy over handle_watcher script
  copy:
    src: files/handle_watcher.sh
    dest: /resinfra/terraform/
    mode: a+x
    owner: consul

- name: set the consul service for auto start
  systemd:
    enabled: yes
    name: consul


- name: ensure consuls .ssh directory exists
  file:
    dest: /home/consul/.ssh
    state: directory
    mode: '700'
    owner: consul


- name: copy public key to consul user
  copy:
    src: "{{pub_key_path}}"
    dest: /home/consul/.ssh/ri_key.pub
    mode: '644'
    owner: consul

- name: copy private key to consul user
  copy:
    src: "{{priv_key_path}}"
    dest: /home/consul/.ssh/ri_key
    mode: '600'
    owner: consul

- name: copy gcp key to consul user
  copy:
    src: "{{gcp_key_path}}"
    dest: /home/consul/.ssh/gcp.json
    mode: '644'
    owner: consul

- name: copy terraform secrets
  copy:
    src: "{{terraform_secret_path}}"
    dest: /resinfra/terraform/terraform.tfvars
    mode: '644'
    owner: consul

