---
- hosts: all
  tasks:
    - name: make sure docker prerequisites are installed
      apt: 
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
          - python3-pip
        state: present
        update_cache: yes

    - name: add docker official gpg key to apt
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
        id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
        state: present

    - name: add docker repo
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: update apt and install docker
      apt:
        update_cache: yes
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present

    - name: install pip docker module to control docker
      pip:
        name: docker

    - name: pull nginx image
      docker_image:
        name: nginx 
        source: pull

    - name: start nginx container
      docker_container:
        name: nginx
        image: nginx
        container_default_behavior: compatibility
        ports: 
          - 80:80
        state: started

