---
- hosts: all
  tasks:
    # todo use ansible.posix.sysctl
    - name: enable kernel packet forwarding
      shell: |-
        sysctl net.ipv4.ip_forward=1
        sysctl net.ipv6.conf.all.forwarding=1
        sysctl net.ipv4.conf.all.accept_redirects=0
        sysctl net.ipv4.conf.all.send_redirects=0
        sysctl -p
        # iptables -A FORWARD -j ACCEPT
      become: yes # is this a good idea?

    - name: install StrongSWAN
      apt:
        name:
          - strongswan
          - libcharon-extra-plugins
        state: present
        update_cache: yes

    - name: configure StrongSWAN
      template:
        src: ipsec.conf.j2
        dest: /etc/ipsec.conf
        mode: 400

    - name: add PSK
      template:
        src: ipsec.secrets.j2
        dest: /etc/ipsec.secrets
        mode: 400

    - name: apply IPSec changes
      shell: ipsec restart; ipsec status
