---
- hosts: gateways
  tasks:
    #sudo sysctl net.ipv4.ip_forward=1
    #sudo sysctl net.ipv6.conf.all.forwarding=1
    #sudo sysctl net.ipv6.conf.all.proxy_ndp=1
    #sudo iptables -A FORWARD -j ACCEPT
    - name: enable kernel packet
      lineinfile:
        path: /etc/sysctl.conf
        line: |-
          net.ipv4.ip_forward = 1
          net.ipv6.conf.all.forwarding = 1
          net.ipv4.conf.all.accept_redirects = 0
          net.ipv4.conf.all.send_redirects = 0
        insertbefore: BOF
    - name: apply sysctl changes
      shell: sysctl -p
    - name: install StrongSWAN
      apt:
        name:
          - strongswan
          - strongswan-swanctl
          - libcharon-extra-plugins
          # strongswan-pki
        state: present
        update_cache: yes
    - name: configure StrongSWAN
      template:
        src: ipsec.conf.j2
        dest: /etc/ipsec.conf
        mode: 400
    - name: add PSK
      template:
        src: ipsec.secrets.j2
        dest: /etc/ipsec.secrets
        mode: 400
    - name: apply IPSec changes
      shell: ipsec restart; ipsec status
    # wait for ipsec status to show ESTABLISHED
