---
- hosts: all # actually only gateway nodes
  tasks:
    # enable kernel packet forwarding
    - ansible.posix.sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        reload: no
    - ansible.posix.sysctl:
        name: net.ipv6.conf.all.forwarding
        value: '1'
        reload: no
    - ansible.posix.sysctl:
        name: net.ipv4.conf.all.accept_redirects
        value: '0'
        reload: no
    - ansible.posix.sysctl:
        name: net.ipv4.conf.all.send_redirects
        value: '0'
        reload: yes

    - name: install StrongSWAN
      apt:
        name:
          - strongswan
          - libcharon-extra-plugins
        state: present
        update_cache: yes

    - name: configure StrongSWAN
      template:
        src: ipsec.conf.j2
        dest: /etc/ipsec.conf
        mode: 400

    - name: add PSK
      template:
        src: ipsec.secrets.j2
        dest: /etc/ipsec.secrets
        mode: 400

    - name: apply IPSec changes
      shell: ipsec restart; ipsec status
